import brevo_python
import os
from brevo_python.rest import ApiException
from langchain_core.tools import tool
from langchain_core.messages import SystemMessage
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_groq import ChatGroq

configuration = brevo_python.Configuration()
configuration.api_key['api-key'] = os.getenv("BREVO_API_KEY")

if "BREVO_API_KEY" not in os.environ:
    os.environ["BREVO_API_KEY"] = getpass.getpass("Enter your Brevo API key: ")
    
email_instructions = """
When the user wants to write or send an email:
    1. First, call `generate_email_body` to create the HTML content.
    2. After receiving the result from `generate_email_body`, use the 'body' field of its output.
    3. Then, call `send_email` with the same subject, the intended recipient, 
       and the value from 'body' as the email HTML.
    4. Do not describe what you are doing — just call the tools directly.
"""

@tool
def send_email(recipient: str, subject: str, body: str) -> str:
    """ Tool that sends an email using Brevo. 
        Args:
            recipient (str): The email address of the recipient.
            subject (str): The subject of the email.
            body (str): The body of the email as html content generated by `generate_email_body` tool.
    """
    api_instance = brevo_python.TransactionalEmailsApi(brevo_python.ApiClient(configuration))
    
    sender = {"name":"Agent - IA","email":"ghostrex2@gmail.com"}
    html_content = f"{body}"
    to = [{"email": f"{recipient}"}]
    cc = [{"email": "ghostrex2@gmail.com"}]
    bcc = [{"email": "ghostrex2@gmail.com"}]
    send_smtp_email = brevo_python.SendSmtpEmail(
        to=to, 
        bcc=bcc, 
        cc=cc, 
        html_content=html_content, 
        sender=sender, 
        subject=f"{subject}"
    ) # SendSmtpEmail | Values to send a transactional email

    try:
        # Send a transactional email
        api_response = api_instance.send_transac_email(send_smtp_email)
        print(api_response)
        return  SystemMessage(content=f"✅ Email successfully sent to {recipient} with subject '{subject}'.")
    except ApiException as e:
        print("Exception when calling TransactionalEmailsApi->send_transac_email: %s\n" % e)
        return SystemMessage(content=f"❌ Failed to send email to {recipient} with subject '{subject}'.")
    
    
generative_model = ChatGoogleGenerativeAI(model="gemini-2.5-flash")
#generative_model = ChatGroq(model="llama-3.1-8b-instant")
@tool
def generate_email_body(subject: str = "", prompt: str = "") -> dict:
    """
    Generate a beautiful HTML email body based on the given context or description.
    Returns a dict so other tools can reuse the result easily.
    """
    full_context = prompt or subject
    if not full_context.strip():
        raise ValueError("generate_email_body requires a non-empty subject or prompt.")

    system_prompt = SystemMessage(
        content=(
            "You are a professional HTML email writer. "
            "Create a well-formatted, attractive, and mobile-friendly HTML email body "
            "based on the given context. "
            "Do NOT include any subject or recipient info. Output only valid HTML content."
        )
    )
    human_message = HumanMessage(content=full_context)

    response = generative_model.invoke([system_prompt, human_message])

    print("=>>>>",response.content)
    # ✅ Return only the content (the actual HTML), not the whole message
    return {"body": response.content}
